### PR TITLE
fix: fixed security issue which cause leakage of API keys to logs

### PR DESCRIPTION
**Pull request by StyleT**
Now for example in Dependency Track logs I see:

```
15:57:17.662 INFO [ProjectResource] Project pkg:npm/internal-app/domains-advanced-dns-application@deploy-production updated by z3KFI9e5d[EDITED]ChhF2
15:57:18.362 INFO [BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: 086f785e-4478-4ac9-886d-349d7281a71b
15:57:18.420 INFO [ProjectResource] Project pkg:npm/internal-app/domains-advanced-dns-application@deploy-production updated by z3KFI9e5d[EDITED]ChhF2
15:57:19.078 INFO [ProjectResource] Project pkg:npm/%40nodejsTools/eslint-config@3.4.1 updated by z3KFI9e5d[EDITED]ChhF2
```

### CODE REVIEW

**Comment by StyleT** [comment]
While this is not the perfect solution to the problem - it's small and covers huge security flaw. 

However refactoring is needed to avoid showing event the part of the key.

**Comment by stevespringett** [comment]
Thanks for the PR

**Comment by StyleT** [comment]
@stevespringett tests should be working now. Pls check. Would be nice to have it released ASAP.

**Comment by StyleT** [comment]
@stevespringett kindly remainder ;)

**Pull request merged**
