### PR TITLE
Use proxy (if provided) for OIDC configuration

### PR DESCRIPTION
**Pull request by zgael**
As discussed in [Dependency Track boards](https://github.com/DependencyTrack/dependency-track/issues/1940), proxies are not supported for OIDC configuration.

As the feature involves multiple projects : 

1. [Dependency Track](https://github.com/DependencyTrack/dependency-track)
2. Alpine (this one)
3. [Oauth-sdk OIDC](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions)

there is not one obivous place where the fix should be done.

I chose to perform everything inside this project as it is closely related to Dependency Track (where the issue is blocking).

Change summary : Instead of calling directly [oauth-sdk's resolve OIDC config](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/src/a6e867c9b38e6d5e946e29fc8d478a455dce0b98/src/main/java/com/nimbusds/openid/connect/sdk/op/OIDCProviderMetadata.java#lines-1876) method, I chose to split it in two steps (that are actually performed internally by the function) : 
- Fetch the config (using basic HTTPRequest with default parameters, where I added the proxy support)
- Call [oauth-sdk's parse method](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/src/a6e867c9b38e6d5e946e29fc8d478a455dce0b98/src/main/java/com/nimbusds/openid/connect/sdk/op/OIDCProviderMetadata.java#lines-1434)

Feel free to discuss, ask questions, request changes if necessary.

### CODE REVIEW

**Comment by zgael** [comment]
Hi @stevespringett, I don't really know how you usually handle your PRs, so allow me to notify you on this one.
Do you need anything more on this topic, explanations, informations ?
I believe there could be a "patched" version of Alpine with this to have it released faster than waiting for a full iteration, but that again depends on your workflow.

Happy to help if needed, don't hesitate to ask.

**Comment by stevespringett** [comment]
@nscuro any input?

**Comment by nscuro** [comment]
Thanks for the PR @zgael!

The same will need to be done for the [`OidcUserInfoAuthenticator`](https://github.com/stevespringett/Alpine/blob/master/alpine-server/src/main/java/alpine/server/auth/OidcUserInfoAuthenticator.java#L45-L49), as it is reaching out to the auth server to validate the token.

We should also consider `ALPINE_NO_PROXY`. It is very common to have a company-internal auth server like Keycloak, for which no proxy must be used. 

Moreover, I think we need to support the standard `HTTP_PROXY` / `HTTPS_PROXY` / `NO_PROXY` environment variables too. [Dependency-Track has logic for this already](https://github.com/DependencyTrack/dependency-track/blob/45868a937f9e5902bee630a2a8c627e459b773d1/src/main/java/org/dependencytrack/common/ManagedHttpClientFactory.java) that we can take inspiration from. @stevespringett, maybe a good opportunity to move the proxy logic to Alpine?

**Comment by stevespringett** [comment]
> maybe a good opportunity to move the proxy logic to Alpine?

Certainly. If its common then it makes sense to move it here.

**Comment by zgael** [comment]
Hi @nscuro, thanks for pointing out what I missed in [OidcUserInfoAuthenticator](https://github.com/stevespringett/Alpine/blob/master/alpine-server/src/main/java/alpine/server/auth/OidcUserInfoAuthenticator.java#L45-L49), nice catch.

Took me some time, but I just pushed another version to take your remarks into account : 

1. Added the same proxy logic to [OidcUserInfoAuthenticator](https://github.com/stevespringett/Alpine/blob/master/alpine-server/src/main/java/alpine/server/auth/OidcUserInfoAuthenticator.java#L45-L49)
2. Factored the proxy logic for the 2 changes I made into a single class (OidcProxyHelper)
3. Took into account NO_PROXY logic, following curl's documentation (since there is no real specification on this). 

I tried writing unit tests to check the proxy logic was working as intended, but it seemed to me it was a bit annoying to mock the config while I was not passing it as parameter of my new class (OidcProxyHelper).
Feel free to give tips on what I could improve if you feel the need to !

**Comment by zgael** [comment]
@nscuro Any news on this topic ?

**Comment by nscuro** [comment]
@zgael Apologies for the long delay, I'll have a look in the next few days.

**Review by nscuro — COMMENTED** [review]
Overall this looks good, but I'd like to get a consistent proxy behavior with how DT does it. I don't think we should maintain such logic in both DT *and* Alpine.

**Pull request closed without merging**
